[package]
name = "doip-sockets"
version = "1.0.0"
authors = ["Samuel Preston <samp.reston@outlook.com>"]
edition = "2021"
description = "A Diagnostics over Internet Protocol (DoIP) implementation for TCP & UDP Sockets with helper functions."
readme = "README.md"
repository = "https://github.com/samp-reston/doip-sockets"
license = "MIT"
keywords = ["doip", "diagnostics", "vehicle", "codec"]
categories = ["development-tools", "network-programming"]

[profile.release]
strip = true      # Automatically strip symbols from the binary.
lto = true
codegen-units = 1
